tracks = [
    { id: 0, title: "23 - Hats!", source: "23-E-Hats.mp3", type: "Extras" },
    { id: 0, title: "35 - Extra Life", source: "35-A.mp3", type: "Ads" },
    { id: 0, title: "35 - McDonalds 1 - Bathroom", source: "35-E-McDonalds-1.mp3", type: "Extras" },
    { id: 0, title: "35 - McDonalds 2 - We're Doing It", source: "35-E-McDonalds-2.mp3", type: "Extras" },
    { id: 0, title: "35 - McDonalds 3 - No Subtitle", source: "35-E-McDonalds-3.mp3", type: "Extras" },
    { id: 0, title: "36 - Phokal Sings Proto News Song", source: "36-N.mp3", type: "News"},
    { id: 0, title: "41 - We're Back We're Back", source: "41-N.mp3", type: "News"},
    { id: 0, title: "41 - Lootcrate Ad", source: "41-A.mp3", type: "Ads" },
    { id: 0, title: "42 - Lootcrate Ad", source: "42-A.mp3", type: "Ads" },
    { id: 0, title: "43 - Snaggle Loves Discord", source: "43-DISCORD-LOVE.mp3", type: "Extras" },
    { id: 0, title: "43 - Snagglewolf Lane", source: "43-E.mp3", type: "Extras" },
    { id: 0, title: "43 - Snaggles GOTY 2016 (Spinach)", source: "43-Spinich.mp3", type: "Extras" },
    { id: 0, title: "44 - Lootcrate Ad", source: "44-A.mp3", type: "Ads"},
    { id: 0, title: "45 - The News Jingle", source: "45-N.mp3", type: "News"},
    { id: 0, title: "49 - Ding Dong The Phokal's Gone!", source: "49-E.mp3", type: "Extras" },
    { id: 0, title: "53 - Gotta Farm It", source: "53-E.mp3", type: "Extras" },
    { id: 0, title: "54 - Dragon Ball Z", source: "54-E.mp3", type: "Extras" },
    { id: 0, title: "54 - Hey Everybody It's The GG News", source: "54-N.mp3", type: "News"},
    { id: 0, title: "55 - News Time", source: "55-N.mp3", type: "News"},
    { id: 0, title: "55 - News Time Extended", source: "55-N-Extended.mp3", type: "News" },
    { id: 0, title: "56 - News You Can Use", source: "56-N.mp3", type: "News"},
    { id: 0, title: "57 - Heeey We're Back, Let's Get Into The News", source: "57-N.mp3", type: "News"},
    { id: 0, title: "59 - It's A News Song, Don't Have The Blues", source: "59-N.mp3", type: "News"},
    { id: 0, title: "59 - Un-Emulatable", source: "59-E.mp3", type: "Extras" },
    { id: 0, title: "61 - What We Forgot", source: "61-N.mp3", type: "News"},
    { id: 0, title: "61 - Game Salts", source: "61-E.mp3", type: "Extras" },
    { id: 0, title: "62 - Wait Wait News News", source: "62-N.mp3", type: "News"},
    { id: 0, title: "62 - Little Nightmares", source: "62-E.mp3", type: "Extras" },
    { id: 0, title: "64 - An Actual Song (Look This UP Later)", source: "64-E.mp3", type: "Extras" },
    { id: 0, title: "65 - News For Me and News For You", source: "65-N.mp3", type: "News"},
    { id: 0, title: "67 - Uhhh Uhhh, Planned This Out, 4 Dudes", source: "67-N.mp3", type: "News"},
    { id: 0, title: "68 - E3 News Song", source: "68-E.mp3", type: "Extras" },
    { id: 0, title: "68 - Pizza Theme", source: "68-N.mp3", type: "News"},
    { id: 0, title: "71 - News Song?, News Today, We Miss Cargen", source: "71-N.mp3", type: "News"},
    { id: 0, title: "73 - Over Top Of Phokal", source: "73-N.mp3", type: "News"},
    { id: 0, title: "75 - We Always Come Back", source: "75-N.mp3", type: "News"},
    { id: 0, title: "75 - News Song 2 (Starting News Again)", source: "75-N-Sequel.mp3", type: "News" },
    { id: 0, title: "75 - Snagglefy", source: "75-Spotify.mp3", type: "Extras" },
    { id: 0, title: "76 - Percussive", source: "76-N.mp3", type: "News"},
    { id: 0, title: "78 - Snaggleman", source: "78-E-Batman.mp3", type: "Extras" },
    { id: 0, title: "78 - Phokal Does a News Song", source: "78-N-With Guests.mp3", type: "News" },
    { id: 0, title: "79 - There Was A News Song", source: "79-N.mp3", type: "News"},
    { id: 0, title: "80 - Cow Windows, It's Not Fine", source: "80-N.mp3", type: "News"},
    { id: 0, title: "81 - Here With Here", source: "81-N.mp3", type: "News"},
    { id: 0, title: "82 - Unlocked This Song In A Box", source: "82-N.mp3", type: "News"},
    { id: 0, title: "82 - Never Gonna Give You Up", source: "82-E.mp3", type: "Extras" },
    { id: 0, title: "82 - Halo 3 Birthday", source: "82-E-Halo.mp3", type: "Extras" },
    { id: 0, title: "83 - At A Normal Hour", source: "83-N.mp3", type: "News"},
    { id: 0, title: "84 - This Is Gonna Be Short", source: "84-N.mp3", type: "News"},
    { id: 0, title: "84 - Extra Life 2017", source: "84-A.mp3", type: "Ads"},
    { id: 0, title: "85 - Hey Everybody It Is Time For The News!", source: "85-N.mp3", type: "News"},
    { id: 0, title: "85 - Extra Life 2017", source: "85-A.mp3", type: "Ads"},
    { id: 0, title: "85 - Always Love You!", source: "85-E-Always Love You.mp3", type: "Extras" },
    { id: 0, title: "86 - Oh A Pianer", source: "86-N.mp3", type: "News"},
    { id: 0, title: "86 - Extra Life 2017", source: "86-A.mp3", type: "Ads"},
    { id: 0, title: "86 - Don't Stop Recording", source: "86-E-Don't Stop Believing.mp3", type: "Extras" },
    { id: 0, title: "86 - Poopen On Your Lawn", source: "86-E-Outro.mp3", type: "Extras" },
    { id: 0, title: "87 - Fast News Song", source: "87-N.mp3", type: "News"},
    { id: 0, title: "87 - Extra Life 2017", source: "87-A.mp3", type: "Ads"},
    { id: 0, title: "88 - 20 Goddamn Minutes", source: "88-N.mp3", type: "News"},
    { id: 0, title: "88 - Oh Wait I Did That Already", source: "88-N-Sequel.mp3", type: "News" },
    { id: 0, title: "89 - News News News News", source: "89-N.mp3", type: "News"},
    { id: 0, title: "90 - It's Time For A News Song", source: "90-N.mp3", type: "News"},
    { id: 0, title: "91 - Beer For News", source: "91-N.mp3", type: "News"},
    { id: 0, title: "92 - Started A While Ago", source: "92-N.mp3", type: "News"},
    { id: 0, title: "93 - Clap Clap It's Time For News", source: "93-N.mp3", type: "News"},
    { id: 0, title: "95 - Don't Get The Blues", source: "95-N.mp3", type: "News"},
    { id: 0, title: "96 - Hey Guys It's Time For The News", source: "96-N.mp3", type: "News"},
    { id: 0, title: "96 - Baba Ba Ba Baba", source: "96-E.mp3", type: "Extras" },
    { id: 0, title: "96 - Ba Ba Baba Ba pffft", source: "96-E-2.mp3", type: "Extras" },
    { id: 0, title: "96 - Diddly De De De De", source: "96-E-3.mp3", type: "Extras" },
    { id: 0, title: "97 - Exhausted", source: "97-N.mp3", type: "News"},
    { id: 0, title: "98 - Cause It's The News Song", source: "98-N.mp3", type: "News"},
    { id: 0, title: "98 - To Find A Host", source: "98-A.mp3", type: "Ads"},
    { id: 0, title: "99 - Pissed Off Lanzo", source: "99-N.mp3", type: "News"},
    { id: 0, title: "99 - To Find A Host", source: "99-A.mp3", type: "Ads"}
];